
name                : Partiguiden
markdown            : kramdown
baseurl             : /
url                 : "https://partiguiden.nu"

include             :  ["/_headers"]
plugins             :
    - jekyll-analytics
    - jekyll-assets
sass:
    sass_dir: _sass
    style: compressed

#Handling reader
safe                : false

#default settings
defaults        :
-
    scope       :
        path    : ""
        type    : artiklar
    values      :
        layout  : partier

#define data collections
collections         :
    artiklar        :
        output      : true
        permalink   : /amnen/:path
        
#Jekyll analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-111642551-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
