name                : Partiguiden
markdown            : kramdown

#Handling reader
safe                : false
include             : ['_pages']

#define data collections
collections         :
    partier         :
        output      : true
        permalink   : /:collection/:path/
    