name                : Partiguiden
markdown            : kramdown
baseurl             : /partiguiden

#Handling reader
safe                : false
include             : ['_pages']

#define data collections

    