name                : Partiguiden
markdown            : kramdown
baseurl             : /partiguiden

sass:
    sass_dir: _sass
    style: compressed

#Handling reader
safe                : false

#default settings
defaults        :
-
    scope       :
        path    : ""
        type    : artiklar
    values      :
        layout  : partier

#define data collections
collections         :
    artiklar        :
        output      : true
        permalink   : /artiklar/:path