---
title: Partiguiden
timezone: UTC
collections:
  artiklar:
    title: Artiklar
    output: true
    permalink: "/artiklar/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  asikter:
    title: Åsikter
    output: true
defaults:
- scope:
    path: ''
    type: artiklar
  values:
    layout: partier
name: Partiguiden
markdown: kramdown
baseurl: "/partiguiden"
sass:
  sass_dir: _sass
  style: compressed
safe: false
